# Name for the workflow
name: Continuous integration

# Select when the actions will be triggered
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  repository_dispatch:

jobs:
  Tests:
    strategy:

      # Do not cancell the rest of the tests if one fails
      fail-fast: false

      # The list of OS and tox environments to be tested
      matrix:
        platform: [ubuntu-latest]
        tox-env: [check, py38, py39]
        include:
          - tox-env: check 
            python-version: 3.8

          - tox-env: py38
            python-version: 3.8

          - tox-env: py39
            python-version: 3.9

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Access the GitHub repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox

    - name: tox -e ${{ matrix.tox-env }}
      run: |
        tox -e ${{ matrix.tox-env }}

  Coverage:
    runs-on: ubuntu-latest 
    needs: Tests

    steps:

      - name: Access the GitHub repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Generate coverage report
        run: |
          python -m pip install --upgrade pip coverage tox
          tox -e py38-coverage
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

